# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    dynamodb_table = "my-lock-table"
    encrypt        = true
    key            = "ItOps-244/euWest-2/llamaDev-Eu/terraform.tfstate"
    region         = "us-east-1"
    bucket         = "llamadev-terragrunt-migration-llamasoft"
  }
}
